### PR TITLE
Fix httpedo13 thermostat card

### PR DESCRIPTION
**Pull request by CM000n**
Hello @httpedo13  here is a pull request that should fix the remaining code formatting issues

### CODE REVIEW

**Comment by edoardop13** [comment]
thank you!😁

**Comment by robbinonline** [comment]
I have a thermostat with the option auto, is there a possibility to get it working with you\re custom card?

**Comment by edoardop13** [comment]
> I have a thermostat with the option auto, is there a possibility to get it working with you\re custom card?

What is the meaning of "auto" mode? I have never tried this mode

**Comment by robbinonline** [comment]
I think it means that the thermostat is following the programmed schedule
IMG_0085

**Comment by edoardop13** [comment]
> I think it means that the thermostat is following the programmed schedule
> IMG_0085

Yes, the card must also work in auto mode. But I didn't understand what this mode does. There isn't much written in the home assistant documentation

**Comment by robbinonline** [comment]
When I try to add this climate devices I get this error.

while scanning for the next token found character '\t' that cannot start any token in

          - type: "custom:button-card"
            template: custom_card_httpedo13_thermostat_with_buttons
            variables:
  	          entity: climate.woonkamer
  	          name: Test

          - type: custom:button-card
            template: custom_card_httpedo13_thermostat_with_buttons
            variables:
  	          entity: climate.woonkamer
  	          name: Test

**Comment by edoardop13** [comment]
> When I try to add this climate devices I get this error.
> 
> while scanning for the next token found character '\t' that cannot start any token in
> 
> ```
>       - type: "custom:button-card"
>         template: custom_card_httpedo13_thermostat_with_buttons
>         variables:
>           entity: climate.woonkamer
>           name: Test
> 
>       - type: custom:button-card
>         template: custom_card_httpedo13_thermostat_with_buttons
>         variables:
>           entity: climate.woonkamer
>           name: Test
> ```

is an indentation error. check tabs and spaces.

**Pull request merged**
